server:
  port: 8081

spring:
  application:
    name: allocation
  datasource:
    username: root
    url: jdbc:mysql://localhost/gs-allocation
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true
    kafka:
      bootstrap-servers: localhost:9092