server:
  port: 8082

spring:
  application:
    name: schedule
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/schedule
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        globally_quoted_identifiers: true
    show-sql: true
    kafka:
      bootstrap-servers: localhost:9092

